- name: Install Kubernetes Binaries (kube-apiserver)
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v{{ k8s_version }}/bin/linux/amd64/kube-apiserver
    dest: /usr/local/bin/
    mode: 0755
    owner: root
    group: root
  tags:
    - binaries


- name: Template Kubernetes Service (kube-apiserver.service)
  template:
    src: templates/kube-apiserver.service.j2
    dest: /etc/systemd/system/kube-apiserver.service
  tags:
    - config
    - service


- systemd:
    name: kube-apiserver
    daemon_reload: yes
    enabled: yes
    state: restarted
  tags:
    - service



