- name: Install Kubernetes Binaries (kube-controller-manager)
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v{{ k8s_version }}/bin/linux/amd64/kube-controller-manager
    dest: /usr/local/bin/
    mode: 0755
    owner: root
    group: root
  tags:
    - binaries


- name: Template Kubernetes Configuration (kube-controller-manager.kubeconfig)
  template:
    src: templates/kube-controller-manager.kubeconfig.j2
    dest: /var/lib/kubernetes/kube-controller-manager.kubeconfig
  tags:
    - config

- name: Template Kubernetes Service (kube-controller-manager.service)
  template:
    src: templates/kube-controller-manager.service.j2
    dest: /etc/systemd/system/kube-controller-manager.service
  tags:
    - config
    - service


- systemd:
    name: kube-controller-manager
    daemon_reload: yes
    enabled: yes
    state: restarted
  tags:
    - service

